# 1. Create a 3x3x3 array with random values 

In [1]:
import numpy as np
b = np.random.random((3,3,3))
print(b)


[[[0.66625872 0.34319015 0.74767127]
  [0.221982   0.59019323 0.77359453]
  [0.94988815 0.54709022 0.42444006]]

 [[0.70690945 0.07981344 0.27502781]
  [0.29528061 0.10161011 0.54641426]
  [0.85882573 0.39186523 0.14034776]]

 [[0.73191109 0.24415387 0.06043509]
  [0.18821446 0.03116896 0.18200376]
  [0.08946607 0.52929697 0.16518806]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [13]:
c = np.eye(5,5)
for i in range(1,5):
    c[i,i-1] = i
print(c)


[[1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [0. 2. 1. 0. 0.]
 [0. 0. 3. 1. 0.]
 [0. 0. 0. 4. 1.]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [22]:
c1 = np.eye(5,5)
for i in range (1,9):
    for j in range (1,9):
        if(i%2==0):
            if(j%2==0):
                 print(0,end=" ")
            else:
                print(1,end=" ")
        else:
            if(j%2==0):
                 print(1,end=" ")
            else:
                print(0,end=" ")
            
    print('\n')

0 1 0 1 0 1 0 1 

1 0 1 0 1 0 1 0 

0 1 0 1 0 1 0 1 

1 0 1 0 1 0 1 0 

0 1 0 1 0 1 0 1 

1 0 1 0 1 0 1 0 

0 1 0 1 0 1 0 1 

1 0 1 0 1 0 1 0 



# 4. Normalize a 5x5 random matrix

In [23]:

arr = np.random.rand(5,5)
print("Array: ",arr)
normal = np.linalg.norm(arr)
normal_array=arr/normal
print("Normalized Array:",normal_array)


Array:  [[0.54706556 0.38689972 0.45538172 0.94057215 0.9199631 ]
 [0.0915428  0.29985893 0.71370492 0.47872074 0.26066112]
 [0.90127498 0.34085607 0.72846584 0.65786098 0.39119965]
 [0.75856856 0.40304063 0.45639916 0.90961318 0.05736729]
 [0.41058173 0.30929437 0.12712392 0.36156537 0.44367591]]
Normalized Array: [[0.19686853 0.13923081 0.16387493 0.33847691 0.33106048]
 [0.03294285 0.10790807 0.25683584 0.17227378 0.09380223]
 [0.32433532 0.12266141 0.26214774 0.23673968 0.1407782 ]
 [0.27298059 0.14503932 0.16424107 0.32733593 0.02064435]
 [0.14775308 0.11130353 0.04574717 0.13011392 0.15966245]]


# 5.  How to find common values between two arrays?

In [24]:
a1 = np.array([1,2,6,3,4,5,7,9])
a2= np.array([11,6,8,12,3,77,30,9,55,81])
print("Common Values: ",np.intersect1d(a1,a2))

Common Values:  [3 6 9]


# 6.How to get the dates of yesterday, today and tomorrow?

In [25]:
import datetime
today=datetime.date.today()
yesterday=today - datetime.timedelta(days=1)
tomorrow = today+datetime.timedelta(days=1)

print("Yesterday: ",yesterday)
print("Today: ",today)
print("Tomorrow: ",tomorrow)


Yesterday:  2020-07-25
Today:  2020-07-26
Tomorrow:  2020-07-27


# 7. Consider two random array A and B, check if they are equal

In [ ]:
a3=np.random.rand(3,3)
a4=np.random.rand(3,3)
print("a3:",a3)
print("a4:",a4)
if (a3==a4).all():
    print("They are equal")
else:
    print("They are not equal")

# 8.Create random vector of size 10 and replace the maximum value by 0 

In [26]:
a = np.random.random(10)
print("Original array:")
print(a)
a[a.argmax()] = 0
print("Maximum value replaced by 0:")
print(a)

Original array:
[0.24161742 0.71199128 0.27974343 0.17735958 0.54325181 0.55599224
 0.75355773 0.09607019 0.06373398 0.83670078]
Maximum value replaced by 0:
[0.24161742 0.71199128 0.27974343 0.17735958 0.54325181 0.55599224
 0.75355773 0.09607019 0.06373398 0.        ]


# 9. How to print all the values of an array?

In [27]:
a6 = np.array([[10,12,30],[11,22,33],[22,55,88]])
print(a6)

[[10 12 30]
 [11 22 33]
 [22 55 88]]


# 10.Subtract the mean of each row of a matrix

In [3]:
import numpy as np
matrix = np.random.rand(3,3)
print(matrix)
new_matrix = matrix - matrix.mean(axis=1,keepdims=True)
print(new_matrix)


[[0.72275329 0.76476258 0.88176326]
 [0.05989026 0.39648137 0.6473163 ]
 [0.31990404 0.85876267 0.78260534]]
[[-0.06700642 -0.02499713  0.09200355]
 [-0.30800572  0.02858539  0.27942032]
 [-0.33385331  0.20500532  0.12884799]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [12]:
import numpy as np
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))


In [13]:
print(Z)

[2. 4. 2. 5. 3. 4. 2. 2. 4. 2.]


# 12.How to get the diagonal of a dot product?

In [5]:
import numpy as np
arr3 = np.random.randint(0,10,(3,3))
arr4= np.random.randint(0,10,(3,3))

print(arr3)
print(arr4)
np.diag(np.dot(arr3, arr4))

[[2 2 1]
 [6 0 7]
 [3 0 6]]
[[9 2 9]
 [5 9 2]
 [1 5 5]]


array([29, 47, 57])

# 13.How to find the most frequent value in an array?

In [6]:
import numpy as np
m = np.random.randint(0,10,10)
print (m)
print('Frequent Number:', np.bincount(m).argmax())


[9 2 3 7 9 6 2 0 4 7]
Frequent Number: 2


# 14.How to get the n largest values of an array

In [8]:
import numpy as np
x=np.arange(45)
print(x)
np.random.shuffle(x)
n=1
print(x[np.argsort(x)[-n:]])
np.max(x)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44]
[44]


44

# 15.How to create a record array from a regular array?

In [10]:
import numpy as np
a =np.array(['Hello','Byee','Hello World'])
b=np.array([10,20,30])
c=np.array(['a','b','c'])
result=np.core.records.fromarrays([a,b,c])


In [11]:
print(result[0])
print(result[1])
print(result[2])


('Hello', 10, 'a')
('Byee', 20, 'b')
('Hello World', 30, 'c')
